### ISSUE TITLE
eureka run returns 500 when machine doesn't exist

### ISSUE THREAD

**Issue by karimodm** [alongalky/eureka-cli-node#6]
Backend log:
```
Error: Machine bla does not exist
    at database.query.then (/home/karimo/eureka/src/eureka/database/tasks.js:31:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
CLI:
```
$ eureka run bla bla bla
Running bla with command bla, output folder is bla
{ message: 'Failed to add task' }
Error: Request failed with status code 500
```

**Comment by karimodm** [comment]
Should return 404
